import { Box, Button, Container, Divider, IconButton, Menu, MenuButton, MenuItem, MenuList, SimpleGrid, Stack, Text } from "@chakra-ui/react";
import { Providers } from "./providers";
import Image from "next/image";
import Link from "next/link";
import { AiOutlineMenu } from "react-icons/ai";
import { MenuIcon } from "./ui/icons";

export const metadata = {
  title: "Referral Haven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" style={{ scrollBehavior: "smooth" }}>
			<body>
				<Providers>
					<Box w="full" position="sticky" bg="white" h="20" shadow="lg">
						<Container maxW="container.xl">
							<Stack h="20" direction="row" justify="space-between" alignItems="center">
								<Link href="/">
									<Image src="/referral-haven-logo.png" height={50} width={200} />
								</Link>

								<Stack display={["none", "none", "none", "flex"]} direction="row" spacing="7" alignItems="center">
									<Link href="/">Home</Link>

									<Link href="/faq">FAQ's</Link>

									<Link href="/about-us">About Us</Link>

									<Link href="/pricing">Pricing</Link>

									<Link href="/preferred">Haven Preferred®</Link>
									
									<Stack direction="row" spacing="4" alignItems="center">
										<Button as={Link} href="https://app.referralhaven.com/sign-up" size="sm" variant="outline" colorScheme="blue" rounded="full">Sign Up</Button>
										<Button as={Link} href="https://app.referralhaven.com/" size="sm" variant="outline" colorScheme="gray" rounded="full">Log In</Button>
									</Stack>
								</Stack>
								
								<Box display={["inline-block", "inline-block", "inline-block", "none"]}>
									<Menu>
										<IconButton variant="ghost" as={MenuButton} icon={<MenuIcon />} />

										<MenuList >
											<MenuItem as={Link} href="/">Home</MenuItem>
											<MenuItem as={Link} href="/faq">FAQ's</MenuItem>
											<MenuItem as={Link} href="/about-us">About Us</MenuItem>
											<MenuItem as={Link} href="/pricing">Pricing</MenuItem>
											<MenuItem as={Link} href="/preferred">Haven Preferred®</MenuItem>
											<Button ml="2" as={Link} href="https://app.referralhaven.com/sign-up" size="md" variant="outline" colorScheme="blue" rounded="full">Sign Up</Button>
											<br />
											<Button mt="2" ml="2" as={Link} href="https://app.referralhaven.com/" size="md" variant="outline" colorScheme="gray" rounded="full">Log In</Button>
										</MenuList>
									</Menu>
								</Box>
							</Stack>
						</Container>
					</Box>
					<Box minH="100vh">
						{children}
					</Box>

					<Box mt='2' py="10" bgColor="gray.800">
						<Container maxW="container.xl">
							<Stack direction={["column", "column", "column", "row"]} justify="space-between" spacing="10">
								<Box>
									<Box p="0.5" bg="white" w="fit-content" borderRadius="5">
										<Image src="/referral-haven-logo.png" width="200" height="100" alt="Referral Haven Logo" />
									</Box>
									<Text fontSize="sm" mt="4" color="white">8430 Wicker Ave <br /> St. John, IN 46373</Text>

									<Text fontSize="sm" mt="10" color="white">© 2024 Referral Haven, LLC. All Rights Reserved.</Text>
									<Text fontSize="sm" color="white">REAL ESTATE LICENSE NUMBER - IN: RC52300045</Text>
								</Box>

								<Box>
									<Text fontSize="xl" color="white">Contact Us</Text>
									<Divider borderColor="white" w="4rem" mb="6" />

									<Text _hover={{ textDecor: "underline" }} fontSize="md" color="white" mb="3"><Link href="tel:(219) 779-5752">(219) 779-5752</Link></Text>
									<Text _hover={{ textDecor: "underline" }} fontSize="md" color="white"><Link href="mailto:admin@referralhaven.com">admin@referralhaven.com</Link></Text>
								</Box>

								<Box>
									<Text fontSize="xl" color="white">Account Links</Text>
									<Divider borderColor="white" w="4rem" mb="6" />

									<Text _hover={{ textDecor: "underline" }} fontSize="md" color="white" mb="3"><Link href="app.referralhaven.com">Dashboard</Link></Text>
									<Text _hover={{ textDecor: "underline" }} fontSize="md" color="white"><Link href="https://billing.stripe.com/p/login/9AQ6r1ebl8LT26Q7ss">Manage Subscription</Link></Text>
								</Box>

								<Box>
									<Text fontSize="xl" color="white">Important Links</Text>
									<Divider borderColor="white" w="4rem" mb="6" />

									<Text _hover={{ textDecor: "underline" }} fontSize="md" color="white" mb="3"><Link href="/">Terms of Service</Link></Text>
									<Text _hover={{ textDecor: "underline" }} fontSize="md" color="white"><Link href="/">Privacy Policy</Link></Text>
								</Box>
							</Stack>
						</Container>
					</Box>

				</Providers>
			</body>
		</html>
	);
}
